[workspace]
resolver = "2"
members = ["fusion", "protocol"]
package.version = "0.51.1"
package.repository = "https://github.com/StardustXR/core/"
package.homepage = "https://stardustxr.org"
package.license = "MIT"

# [patch."https://github.com/technobaboo/gluon"]
# gluon.path = "../gluon/wire"
# gluon-codegen.path = "../gluon/codegen-rust"
