[package]
edition = "2024"
rust-version = "1.85"
name = "stardust-xr-fusion"
authors = ["Nova King <technobaboo@proton.me>"]
description = "High level client library for the Stardust XR display server"
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = []
serde = ["stardust-xr-protocol/serde"]

[dependencies]
glam.workspace = true
tracing.workspace = true
gluon-ipc.workspace = true
stardust-xr-protocol.workspace = true
parking_lot = "0.12.1"
thiserror = "2.0.16"
tokio = { version = "1.53.1", features = [
	"sync",
	"macros",
	"rt",
	"time",
	"net",
	"io-util",
	"signal",
] }
xdg = "3.0.0"
rustix = { version = "1.1.4", features = ["fs"] }

[dev-dependencies]
tracing-subscriber = "0.3.17"
