[package]
edition = "2024"
rust-version = "1.85"
name = "stardust-xr-fusion"
authors = ["Nova King <technobaboo@proton.me>"]
description = "High level client library for the Stardust XR display server"
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = []
serde = ["stardust-xr-protocol/serde"]

[dependencies]
glam = { version = "0.30.0", features = ["mint"] }
parking_lot = "0.12.1"
thiserror = "2.0.16"
tokio = { version = "1.38.0", features = [
	"sync",
	"macros",
	"rt",
	"time",
	"net",
	"io-util",
	"signal",
] }
tracing = "0.1.37"
stardust-xr-protocol = { version = "0.51.0", path = "../protocol" }
gluon = { git = "https://github.com/technobaboo/gluon", features = [
	"tracing",
] }
pion-binder = { git = "https://github.com/technobaboo/pion" }
xdg = "3.0.0"

[dev-dependencies]
tracing-subscriber = "0.3.17"
